# Generated by Django 3.1 on 2021-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tw_id',
            field=models.CharField(default='', max_length=280, unique=True),
        ),
    ]
