# Generated by Django 3.1 on 2021-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210618_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='fav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ret',
            field=models.IntegerField(default=0),
        ),
    ]
