# Generated by Django 3.1 on 2021-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tweet_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(default='', max_length=280, unique=True)),
                ('name', models.CharField(default='', max_length=280, unique=True)),
            ],
        ),
    ]
