# Generated by Django 3.1 on 2021-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tw_id',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='usr_id',
            field=models.CharField(default='', max_length=280),
        ),
    ]
