# Generated by Django 3.1 on 2021-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210618_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tw_id',
            field=models.CharField(default='', max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='usr_id',
            field=models.CharField(default='', max_length=280, unique=True),
        ),
    ]
