# Generated by Django 3.2.18 on 2023-04-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210618_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='usr_id',
            new_name='scr',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='ret',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='name',
        ),
    ]
