# Generated by Django 3.2.18 on 2023-04-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='', max_length=280),
        ),
    ]
